/*
Copyright (c) 2026 Nauel Gómez Gamero
Licensed under the Business Source License 1.1
*/

import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import { runInitAi } from '../dist/plugin/cli/init-ai.js';

async function withTempProject(fn) {
  const tempRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'astro-blocks-cli-'));
  try {
    await fn(tempRoot);
  } finally {
    await fs.rm(tempRoot, { recursive: true, force: true });
  }
}

const IDEMPOTENCY_STRING = 'node_modules/@astroblocks/astro-blocks/AGENTS.consumer.md';

// Scenario 1 — Fresh project: creates AGENTS.md with reference
test('init-ai: fresh project creates AGENTS.md with reference', async () => {
  await withTempProject(async (tempRoot) => {
    await runInitAi(tempRoot, {});

    const agentsPath = path.join(tempRoot, 'AGENTS.md');
    const stat = await fs.stat(agentsPath).catch(() => null);
    assert.ok(stat !== null, 'AGENTS.md should be created');

    const content = await fs.readFile(agentsPath, 'utf-8');
    assert.ok(
      content.includes(IDEMPOTENCY_STRING),
      `AGENTS.md should contain the idempotency string: ${IDEMPOTENCY_STRING}`
    );
  });
});

// Scenario 2 — Existing AGENTS.md: appends section, preserves content
test('init-ai: existing AGENTS.md appends section and preserves original content', async () => {
  await withTempProject(async (tempRoot) => {
    const originalContent = '# My Project\n\nsome content';
    const agentsPath = path.join(tempRoot, 'AGENTS.md');
    await fs.writeFile(agentsPath, originalContent, 'utf-8');

    await runInitAi(tempRoot, {});

    const content = await fs.readFile(agentsPath, 'utf-8');
    assert.ok(content.includes(originalContent), 'Original content should be preserved');
    assert.ok(content.includes(IDEMPOTENCY_STRING), 'Reference section should be appended');

    // Exactly one reference section inserted
    const sectionHeader = '## AI Context from Dependencies';
    const sections = content.split(sectionHeader).length - 1;
    assert.equal(sections, 1, 'Reference section should appear exactly once');
  });
});

// Scenario 3 — Existing CLAUDE.md, no AGENTS.md: appends to CLAUDE.md
test('init-ai: existing CLAUDE.md and no AGENTS.md → appends to CLAUDE.md', async () => {
  await withTempProject(async (tempRoot) => {
    const claudePath = path.join(tempRoot, 'CLAUDE.md');
    await fs.writeFile(claudePath, '# CLAUDE\n\nmy instructions', 'utf-8');

    await runInitAi(tempRoot, {});

    const claudeContent = await fs.readFile(claudePath, 'utf-8');
    assert.ok(claudeContent.includes(IDEMPOTENCY_STRING), 'CLAUDE.md should contain the reference');

    // AGENTS.md should NOT have been created
    const agentsStat = await fs.stat(path.join(tempRoot, 'AGENTS.md')).catch(() => null);
    assert.equal(agentsStat, null, 'AGENTS.md should NOT be created when CLAUDE.md exists');
  });
});

// Scenario 4 — Idempotency: running twice inserts reference exactly once
test('init-ai: idempotency — running twice results in exactly one reference', async () => {
  await withTempProject(async (tempRoot) => {
    await runInitAi(tempRoot, {});
    await runInitAi(tempRoot, {});

    const agentsPath = path.join(tempRoot, 'AGENTS.md');
    const content = await fs.readFile(agentsPath, 'utf-8');
    const sectionHeader = '## AI Context from Dependencies';
    const sections = content.split(sectionHeader).length - 1;
    assert.equal(sections, 1, 'Reference section should appear exactly once after two runs');
  });
});

// Scenario 5 — --copy flag: embeds content inline
test('init-ai: --copy flag embeds content with version comment', async () => {
  await withTempProject(async (tempRoot) => {
    await runInitAi(tempRoot, { copy: true });

    const agentsPath = path.join(tempRoot, 'AGENTS.md');
    const content = await fs.readFile(agentsPath, 'utf-8');

    assert.ok(
      content.includes('Generated by astro-blocks init-ai'),
      'Copy mode should include generation comment'
    );

    // Should NOT contain a bare Markdown link to the node_modules path
    // (content is embedded inline, not a reference link)
    assert.ok(
      !content.includes('](./node_modules/@astroblocks/astro-blocks/AGENTS.consumer.md)'),
      'Copy mode should NOT contain a bare Markdown link to node_modules path'
    );
  });
});

// Scenario 6 — Resolver failure via _resolverOverride: silent fallback to copy mode
test('init-ai: _resolverOverride failure falls back to copy mode silently', async () => {
  await withTempProject(async (tempRoot) => {
    const failingResolver = () => {
      throw new Error('PnP resolution failure');
    };

    // Should not throw — should fall back to copy mode
    await runInitAi(tempRoot, { _resolverOverride: failingResolver });

    const agentsPath = path.join(tempRoot, 'AGENTS.md');
    const stat = await fs.stat(agentsPath).catch(() => null);
    assert.ok(stat !== null, 'AGENTS.md should still be created on resolution failure');

    const content = await fs.readFile(agentsPath, 'utf-8');
    assert.ok(
      content.includes(IDEMPOTENCY_STRING),
      'File should contain content (copy fallback) with the idempotency string'
    );
  });
});
